exclude: '^$'
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-toml
  - id: end-of-file-fixer
  - id: name-tests-test
